import { Injectable, InternalServerErrorException, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { promises as fs } from 'fs';
import * as path from 'path';
import { v4 as uuidv4 } from 'uuid';
import { categoryForMimeType, extensionForMimeType, UPLOAD_FOLDERS } from './storage.constants';
import { StorageDriver, StorageDriverName, StoredObject, UploadFile } from './storage.types';

/**
 * Writes uploads to the local filesystem under `UPLOAD_DIR`.
 *
 * Layout: <root>/<folder>/<YYYY>/<MM>/<uuid>.<ext>
 *
 * Year/month sharding keeps directory listings manageable and makes
 * date-scoped archival or cleanup straightforward later.
 */
@Injectable()
export class LocalDiskDriver implements StorageDriver {
  readonly name: StorageDriverName = 'local';

  private readonly logger = new Logger(LocalDiskDriver.name);
  private readonly root: string;
  private readonly publicBaseUrl: string;
  private readonly publicPathPrefix: string;

  constructor(private config: ConfigService) {
    // Resolved absolute so it can never land inside dist/, which is wiped on
    // every rebuild - that would take all uploaded files with it.
    this.root = path.resolve(this.config.get<string>('storage.uploadDir') || './uploads');
    this.publicBaseUrl = (
      this.config.get<string>('storage.publicBaseUrl') || 'http://localhost:4000'
    ).replace(/\/+$/, '');
    this.publicPathPrefix = this.config.get<string>('storage.publicPathPrefix') || '/uploads';
  }

  async put(file: UploadFile, folder: string): Promise<StoredObject> {
    const safeFolder = this.assertAllowedFolder(folder);

    const now = new Date();
    const year = String(now.getUTCFullYear());
    const month = String(now.getUTCMonth() + 1).padStart(2, '0');

    // Filename is always a fresh UUID and the extension comes from the MIME
    // map - never from the client-supplied name, which is the standard
    // path-traversal and silent-overwrite vector.
    const fileName = `${uuidv4()}.${extensionForMimeType(file.mimeType)}`;
    const storageKey = `${safeFolder}/${year}/${month}/${fileName}`;
    const absolutePath = this.assertInsideRoot(storageKey);

    try {
      await fs.mkdir(path.dirname(absolutePath), { recursive: true });
      await fs.writeFile(absolutePath, file.buffer);
    } catch (error) {
      this.logger.error(`Failed to write ${storageKey}: ${(error as Error).message}`);
      throw new InternalServerErrorException('Failed to store the uploaded file');
    }

    return {
      storageKey,
      url: this.publicUrl(storageKey),
      sizeBytes: file.buffer.byteLength,
      mimeType: file.mimeType,
      category: categoryForMimeType(file.mimeType)!,
    };
  }

  async delete(storageKey: string): Promise<void> {
    let absolutePath: string;
    try {
      absolutePath = this.assertInsideRoot(storageKey);
    } catch {
      // A key that escapes the root is never something we wrote - refuse
      // quietly rather than unlinking whatever it points at.
      this.logger.warn(`Refusing to delete out-of-root storage key: ${storageKey}`);
      return;
    }

    try {
      await fs.unlink(absolutePath);
    } catch (error) {
      const code = (error as NodeJS.ErrnoException).code;
      if (code !== 'ENOENT') {
        // Deleting media must never break the request that triggered it - the
        // DB row is the record that matters. Orphan files are reconcilable.
        this.logger.error(`Failed to delete ${storageKey}: ${(error as Error).message}`);
      }
    }
  }

  publicUrl(storageKey: string): string {
    return `${this.publicBaseUrl}${this.publicPathPrefix}/${storageKey}`;
  }

  localPath(storageKey: string): string | null {
    try {
      return this.assertInsideRoot(storageKey);
    } catch {
      return null;
    }
  }

  /** The uploads root, for wiring static serving in main.ts. */
  getRoot(): string {
    return this.root;
  }

  private assertAllowedFolder(folder: string): string {
    if (!(UPLOAD_FOLDERS as readonly string[]).includes(folder)) {
      throw new InternalServerErrorException(`Unknown upload folder: ${folder}`);
    }
    return folder;
  }

  /**
   * Keys are generated by this class, but delete/localPath receive them back
   * from the database, so containment is re-verified rather than assumed.
   */
  private assertInsideRoot(storageKey: string): string {
    const absolutePath = path.resolve(this.root, storageKey);
    const rootWithSep = this.root.endsWith(path.sep) ? this.root : this.root + path.sep;

    if (!absolutePath.startsWith(rootWithSep)) {
      throw new InternalServerErrorException('Resolved path escapes the storage root');
    }
    return absolutePath;
  }
}
